# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: source.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csource.proto\x12\x04grpc\"%\n\x07Relogio\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x01\"\'\n\x05\x43\x61rta\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x10\n\x08mensagem\x18\x02 \x01(\t\"\x06\n\x04Nada2\x87\x01\n\x04\x63hat\x12)\n\x0creceberCarta\x12\n.grpc.Nada\x1a\x0b.grpc.Carta0\x01\x12\'\n\x0cremeterCarta\x12\x0b.grpc.Carta\x1a\n.grpc.Nada\x12+\n\x0eremeterRelogio\x12\r.grpc.Relogio\x1a\n.grpc.Nadab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'source_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RELOGIO']._serialized_start=22
  _globals['_RELOGIO']._serialized_end=59
  _globals['_CARTA']._serialized_start=61
  _globals['_CARTA']._serialized_end=100
  _globals['_NADA']._serialized_start=102
  _globals['_NADA']._serialized_end=108
  _globals['_CHAT']._serialized_start=111
  _globals['_CHAT']._serialized_end=246
# @@protoc_insertion_point(module_scope)
