# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.source_pb2 as source__pb2


class chatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.receberCarta = channel.unary_stream(
                '/grpc.chat/receberCarta',
                request_serializer=source__pb2.Nada.SerializeToString,
                response_deserializer=source__pb2.Carta.FromString,
                )
        self.remeterCarta = channel.unary_unary(
                '/grpc.chat/remeterCarta',
                request_serializer=source__pb2.Carta.SerializeToString,
                response_deserializer=source__pb2.Nada.FromString,
                )
        self.remeterRelogio = channel.unary_unary(
                '/grpc.chat/remeterRelogio',
                request_serializer=source__pb2.Relogio.SerializeToString,
                response_deserializer=source__pb2.Nada.FromString,
                )


class chatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def receberCarta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def remeterCarta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def remeterRelogio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_chatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'receberCarta': grpc.unary_stream_rpc_method_handler(
                    servicer.receberCarta,
                    request_deserializer=source__pb2.Nada.FromString,
                    response_serializer=source__pb2.Carta.SerializeToString,
            ),
            'remeterCarta': grpc.unary_unary_rpc_method_handler(
                    servicer.remeterCarta,
                    request_deserializer=source__pb2.Carta.FromString,
                    response_serializer=source__pb2.Nada.SerializeToString,
            ),
            'remeterRelogio': grpc.unary_unary_rpc_method_handler(
                    servicer.remeterRelogio,
                    request_deserializer=source__pb2.Relogio.FromString,
                    response_serializer=source__pb2.Nada.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class chat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def receberCarta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.chat/receberCarta',
            source__pb2.Nada.SerializeToString,
            source__pb2.Carta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def remeterCarta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.chat/remeterCarta',
            source__pb2.Carta.SerializeToString,
            source__pb2.Nada.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def remeterRelogio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.chat/remeterRelogio',
            source__pb2.Relogio.SerializeToString,
            source__pb2.Nada.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
